language: python
python:
- 3.8
#- "3.10-dev"
#- 3.9
#- 3.7
#- 3.6
install: pip install -U tox-travis
script: tox
before_deploy:
- pip install -r requirements_dev.txt
- apt-get update
- apt-get install -y openssl
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  skip_existing: true
  on:
    repo: BioLM/py-biolm
    python: 3.8
    branch: production
  username: "__token__"
  password:
    secure: yCDjiKw7Kro+qZNsG7L2GquPp9ZVAlFKtJKnCDy7LHobapSeGWe5dfZ9ez/E7EfSkOZMlqTJVsEgxZaU6x72mMBh3wUilCFLIQgU1aHcN8bw8LPPzSEdJINYTx4xQXr7IAPMF26VmtvfaTjW5HRn1NRuwMiORJd++uAwiKKMBt5TyqGDS7f3UqmbjXCgirm/eiwZ/FVuiBPOa7IM4DPLWCR48d8rZfuvcSMkdv4ofbw30eYwaJerEXGS4d+DyeHX46NYS65g8TZDvtvXMTw3gw42T/iUVU0jtziQIc8fpwEjijwwnFEQyegeBo6siUaRlBQSzhazpAfiGdMHtNJpmwjyNleQnECjwCEW4Hi0K0iXjr869ZAvMGErYEnMCsWFf/UMhrZ64H+T1cjqkwW05uv4zYK2t8AKDUu9PR3LkBiaah98goO/COp/uOmMlUDBkGAYEVgZuH0ezeDgSd83CbzSSs8cwrdPz3nYL/pcWpOATUIqu4uilOw0EFywiFfbOcKrphN9XRVriCC3jD++HPuY5mM7u7scMj+Rh8NQPkD6xBzLTN4Su1Htfeu2g1wo06NiHMxsWcrrdi42bDnvK5Xsfz3Bk5U+vKfMMtOes6OP6YYt/gd+57lHSXEHumlx/EIAns3SIo1sb+389LGZqQ1vPBOAR6lpXt+BGNkxcbI=
env:
  global:
  - secure: en3cOLK1UYyOXN1Q4J4+OGHj1khenQ807D4/QUJBXHRCblg/GYei9XKMq3uBJvUit1B9JL2tULCziO1q9KDkFT9rrfbWSbvfl28GD9LFGBW9Gbqb4/26b2y8r8MU+QXByGbniDSAneArhDvtq4IUo8H9hkIiPseK1P+A0lvWnJiP6gFais5umGtlzt/faYaCQhLoOKXzbbnGsOcGfcmmBc4Ps2FFrVXr8Lp7bg7qte7rvLio4K2yK/v36oBJ25ZOQzJema+1eCBRtWOEmnh4ptaJ+55CAhjpssdBTSmaegqFLXBJmCHiZyR+Q9tUeHUFxL9iJlWaj8saK0qBo93HuCkaVuVes0V1fMwWgiIhgd6DrCj5bXENaMhaxKsuC1xqZiDfSipL+B4Goqut2heJoVPVgYM445mvmH1OqUv8++I8BghJ0RqPhRS8V6qL7nMazR+DF6ZDQF4YGVyYXMYVrGqwZ/xcArIRf6ehonXzDJewyJs+LfXQKQwGpQFclsKYHOsHbjGxWlKaBzdA+ZtE9u6wdknIzE7HCTKSgeu7VcpInw5WDfX7szehOFyH92t3u8KZFvQhRf4yIhOXJdrX/Zy/EvQjAJlJkm9E297BxCtEwwvIbjMyxnHqUvqoD2XnI2omoR+zjFvBkt9b6Rgb2IJvC5xb+3pJ++4CNL48+IM=
  - secure: bW0y/ntnPcXSCfrVX5LdpZmws4CpRz4qZCmEEMx/4L/QTTzGd+9IbQw0kcv7WQ8S6Wc0MYv0IKvaAbWYihO0BC3KXkOUy5u/iQcGcspkyJ75c/szE3wsNt5FvnpKOntrC0pHNr5xy61w8zmL9EuTYqTxTAaRbff5rYAJjLtMYayFZdbdoTFnuwCwzBbkRbI2ySvFCtxg3acXeHVtOY1DwvIbzvODVh14xH2PSqaC+oJdd6wPDDIZro1k4/FprABTR7Zc13Lp4y9VmWXpXhlGi8QqcdNLSacQuhpIxUE4t5pvZqV0aZqr3BScOoHGA3YTHOpJpQHllDE7Ur4AE/fm6/pafT640demAebMgmno3E5E+FdKLsPN+ctY+hlf0bGLUPJbnoOTsahQ7RRqvP6vBRrTnD6eI/LZTdWZVIRQrb8rm1T8gas4/s4w9u4JcojEIv4iX6GqGxuoSo/gZP3nQiAd7fggbZ8QbVh/G94/EENpwv3mWs2jvV82S/5gN1IV+KcMRVsVLo4ClFowi4tMy+YFFRtLIeIajat6gfilgzwosFf46nG1+QUWaYvO7ZlhXWJ9VhP1u+DdSBdgbybfJfkIlo2e1ZTQCIK10phxeGDlW/F3WQr8YUW/SgN1VuX6RIldngL8IO0vyOoavWxxv7JN5KiqyrAfL0xEAViV9tc=
