language: python
python:
- "3.10-dev"
- 3.9
- 3.8
- 3.7
- 3.6
before_install:
- sudo apt-get install -y python-dev || true
- sudo apt-get install -y python3-dev python-dev
- sudo apt-get install -y python-distutils || true
- sudo apt-get install -y python3-distutils || true
- sudo apt-get install -y python3-distutils-extra || true
- sudo apt-get install -y python3.7-distutils || true
- sudo apt-get install -y python3.6-distutils || true
install:
- pip install docutils
- pip install 'tox-travis<=0.13' setuptools wheel
- pip install -r requirements_dev.txt
script: RS=118 make test
after_success: make install
before_deploy: pip install -U -r requirements_dev.txt
deploy:
  edge: true
  provider: script
  script: bash deploy.sh
  cleanup: true
  on:
    repo: BioLM/py-biolm
    python: "3.9"
    branch: production
env:
  global:
    - secure: en3cOLK1UYyOXN1Q4J4+OGHj1khenQ807D4/QUJBXHRCblg/GYei9XKMq3uBJvUit1B9JL2tULCziO1q9KDkFT9rrfbWSbvfl28GD9LFGBW9Gbqb4/26b2y8r8MU+QXByGbniDSAneArhDvtq4IUo8H9hkIiPseK1P+A0lvWnJiP6gFais5umGtlzt/faYaCQhLoOKXzbbnGsOcGfcmmBc4Ps2FFrVXr8Lp7bg7qte7rvLio4K2yK/v36oBJ25ZOQzJema+1eCBRtWOEmnh4ptaJ+55CAhjpssdBTSmaegqFLXBJmCHiZyR+Q9tUeHUFxL9iJlWaj8saK0qBo93HuCkaVuVes0V1fMwWgiIhgd6DrCj5bXENaMhaxKsuC1xqZiDfSipL+B4Goqut2heJoVPVgYM445mvmH1OqUv8++I8BghJ0RqPhRS8V6qL7nMazR+DF6ZDQF4YGVyYXMYVrGqwZ/xcArIRf6ehonXzDJewyJs+LfXQKQwGpQFclsKYHOsHbjGxWlKaBzdA+ZtE9u6wdknIzE7HCTKSgeu7VcpInw5WDfX7szehOFyH92t3u8KZFvQhRf4yIhOXJdrX/Zy/EvQjAJlJkm9E297BxCtEwwvIbjMyxnHqUvqoD2XnI2omoR+zjFvBkt9b6Rgb2IJvC5xb+3pJ++4CNL48+IM=
    - secure: bW0y/ntnPcXSCfrVX5LdpZmws4CpRz4qZCmEEMx/4L/QTTzGd+9IbQw0kcv7WQ8S6Wc0MYv0IKvaAbWYihO0BC3KXkOUy5u/iQcGcspkyJ75c/szE3wsNt5FvnpKOntrC0pHNr5xy61w8zmL9EuTYqTxTAaRbff5rYAJjLtMYayFZdbdoTFnuwCwzBbkRbI2ySvFCtxg3acXeHVtOY1DwvIbzvODVh14xH2PSqaC+oJdd6wPDDIZro1k4/FprABTR7Zc13Lp4y9VmWXpXhlGi8QqcdNLSacQuhpIxUE4t5pvZqV0aZqr3BScOoHGA3YTHOpJpQHllDE7Ur4AE/fm6/pafT640demAebMgmno3E5E+FdKLsPN+ctY+hlf0bGLUPJbnoOTsahQ7RRqvP6vBRrTnD6eI/LZTdWZVIRQrb8rm1T8gas4/s4w9u4JcojEIv4iX6GqGxuoSo/gZP3nQiAd7fggbZ8QbVh/G94/EENpwv3mWs2jvV82S/5gN1IV+KcMRVsVLo4ClFowi4tMy+YFFRtLIeIajat6gfilgzwosFf46nG1+QUWaYvO7ZlhXWJ9VhP1u+DdSBdgbybfJfkIlo2e1ZTQCIK10phxeGDlW/F3WQr8YUW/SgN1VuX6RIldngL8IO0vyOoavWxxv7JN5KiqyrAfL0xEAViV9tc=
